### ISSUE TITLE
Peer to Peer Group Code Review

### ISSUE THREAD

**Issue by amrendrakind** [Hadi111jafari/capstone2-API-webapp#47]
@memelopez and @Hadi111jafari Team you are doing awesome work.

- Please consider removing unused code so that it will have clean code
  - https://github.com/Hadi111jafari/capstone2-API-webapp/blob/8c9bdf4a7b9c86d57b6f14ada2efcb07ac9d53c2/src/index.js#L47-L49

**Comment by zkr024** [comment]
* your project is going well.
* you might add in CSS a backdrop-filter: for the modal. That will look great.
